#!/usr/bin/env python
'''
Script to initialize an IPython session with all the classes and functions from
"jobmgr" being loaded.
'''

# Python
import inspect

# IPython
try:
    import IPython
except:
    raise RuntimeError('IPython is not available')

from traitlets.config.loader import Config

# Local
import jobmgr

# Display message
message = '''
Welcome to "jobmgr" version {}
Access the job manager via "jobs"

Documentation is available at:
https://mramospe.github.io/jobmgr/

For issues, questions and contributions, please visit:
https://github.com/mramospe/jobmgr
'''.format(jobmgr.version.__version__)

# Extract all the classes and functions from "jobmgr"
avars = {}
for n in jobmgr.__all__:

    a = getattr(jobmgr, n)

    if not inspect.ismodule(a):
        avars[n] = a

# Initialize the context manager
with jobmgr.ContextManager() as jobs:

    # "jobs" will hold the ContextManager jobs
    avars['jobs'] = jobs

    # Start IPython session
    cfg = Config()
    cfg.TerminalInteractiveShell.banner1 = message

    IPython.start_ipython(config=cfg, user_ns=avars)
