#!/usr/bin/env python
'''
Script to initialize an IPython session with all the classes and functions from
"jobmgr" being loaded.
'''

# Python
import inspect

# IPython
try:
    import IPython
except:
    raise RuntimeError('IPython is not available')

from traitlets.config.loader import Config

# Local
import jobmgr

# Initialize the job manager
jobs = jobmgr.JobManager()

# Start IPython session
cfg = Config()
cfg.TerminalInteractiveShell.banner1 = '''
Welcome to "jobmgr" version {}
Access the job manager via "jobs"

Documentation is available at:
https://mramospe.github.io/jobmgr/

For issues, questions and contributions, please visit:
https://github.com/mramospe/jobmgr
'''.format(jobmgr.version.__version__)

avars = {'jobs': jobs}
for n in jobmgr.__all__:

    a = getattr(jobmgr, n)

    if not inspect.ismodule(a):
        avars[n] = a

IPython.start_ipython(config=cfg, user_ns=avars)
