#!/usr/bin/env python
'''
Script to initialize an IPython session with all the classes and functions from
"stepped_job" being loaded.
'''

# Python
import inspect

# IPython
try:
    import IPython
except:
    raise RuntimeError('IPython is not available')

from traitlets.config.loader import Config

# Local
import stepped_job

# Initialize the job manager
jobs = stepped_job.JobManager()

# Start IPython session
cfg = Config()
cfg.TerminalInteractiveShell.banner1 = '''
Welcome to "stepped_job" version {}
Access the job manager via "jobs"

Documentation is available at:
https://mramospe.github.io/stepped_job/

For issues, questions and contributions, please visit:
https://github.com/mramospe/stepped_job
'''.format(stepped_job.version.__version__)

avars = {'jobs': jobs}
for n in stepped_job.__all__:

    a = getattr(stepped_job, n)

    if not inspect.ismodule(a):
        avars[n] = a

IPython.start_ipython(config=cfg, user_ns=avars)
